# Generated by Django 6.1.1 on 2026-09-15 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_groupstudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('payment_type', models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Karta orqali'), ('CLICK', 'Click / Payme')], default='CARD', max_length=10, verbose_name="To'lov turi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="To'langan vaqti")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
        ),
    ]
