# Generated by Django 6.1.1 on 2026-09-15 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'm)")),
                ('duration_months', models.PositiveIntegerField(default=1, verbose_name='Davomiyligi (oy)')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Guruh nomi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.course', verbose_name='Kurs')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'MENTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_groups', to=settings.AUTH_USER_MODEL, verbose_name='Mentor')),
            ],
        ),
    ]
