# Generated by Django 6.1.1 on 2026-09-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_groupstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dars sanasi')),
                ('is_present', models.BooleanField(default=True, verbose_name='Keldi/Kelmadi')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Uy vazifasi bali (0-100)')),
                ('group_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.groupstudent', verbose_name='Talaba')),
            ],
            options={
                'unique_together': {('group_student', 'date')},
            },
        ),
    ]
